# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
      BOT_PREFIX: ${{ secrets.BOT_PREFIX }}
      DEFAULT_ACCOUNT: ${{ secrets.DEFAULT_ACCOUNT }}
      HIBP_API_KEY: ${{ secrets.HIBP_API_KEY }}
      APP_NAME: ${{ secrets.APP_NAME }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 mypy types-requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Static type checking with mypy
      run: |
        python -m mypy --strict .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=13 --max-line-length=127 --statistics

